-- models/staging/source.sql
{{ config(materialized='view') }}

SELECT id,
       source_file,
       inserted_at,
       blob_filename,
       timestamp,
       f_in,
       c_in,
       f_in_pst_1,
       f_in_pst_2,
       c_in_pst_1,
       c_in_pst_2,
       f_out_pst_1,
       f_out_pst_2,
       c_out_pst_1,
       c_out_pst_2,
       c_pst_1,
       c_pst_2,
       f_underflow_pst_1,
       f_underflow_pst_2,
       f_in_ast_1,
       f_in_ast_2,
       c_in_ast_1,
       c_in_ast_2,
       f_ox_in_ast_1,
       f_ox_in_ast_2,
       f_out_ast_1,
       f_out_ast_2,
       c_out_ast_1,
       c_out_ast_2,
       c_ast_1,
       c_ast_2,
       d_ast_1,
       d_ast_2,
       f_ox_out_ast_1,
       f_ox_out_ast_2,
       f_in_sst_1,
       c_in_sst_1,
       f_out_sst_1,
       c_out_sst_1,
       c_sst_1,
       f_underflow_sst_1,
       t

FROM {{ source('postgres', 'blob_data_ingest') }}
